name: leap
description: An opinionated toolkit for creating 2D platformers on top of Flame engine.
version: 0.1.0
homepage: https://github.com/kurtome/leap

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.13.2

dependencies:
  flame: ^1.10.0
  flame_behaviors: ^0.2.0
  flame_tiled: ^1.14.1
  flutter:
    sdk: flutter
  tiled: ^0.10.1

dev_dependencies:
  flame_lint: ^1.1.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      path: packages/flame
  flame_behaviors:
    git:
      url: https://github.com/VeryGoodOpenSource/flame_behaviors
      ref: feat!(flame_behaviors)-migrate-to-flame-v1.8.0
      path: packages/flame_behaviors
  flame_tiled:
    git:
      url: https://github.com/flame-engine/flame.git
      path: packages/flame_tiled
